import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy | MyResolveCenter", description: "How MyResolveCenter collects, uses and protects account and recovery-case information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" intro="This policy explains what information MyResolveCenter collects, why we use it and the choices available to you.">
    <section><h2>Who we are</h2><p>MyResolveCenter is a product by Elegant Empire AI. Privacy questions and requests can be sent to <a className="font-semibold text-[#0b6b53] underline" href="mailto:contact@myresolvecenter.com">contact@myresolvecenter.com</a>.</p></section>
    <section><h2>Information we collect</h2><ul><li>Account information, including your email address and display name.</li><li>Case details you enter, such as merchant, amount, currency, dates and the problem you experienced.</li><li>Evidence you choose to upload, including receipts, screenshots, invoices and merchant responses.</li><li>Generated drafts, evidence assessments, case events and follow-up information.</li><li>Basic technical and security information needed to operate and protect the service.</li></ul><p className="mt-3">Please remove unrelated information and avoid uploading passwords, full card numbers, government identification or information about other people unless it is genuinely necessary.</p></section>
    <section><h2>How we use information</h2><ul><li>To create and maintain your account and private recovery cases.</li><li>To extract transaction details, assess evidence and generate requested documents.</li><li>To provide support, prevent abuse and maintain service security.</li><li>To improve company routes and product performance using aggregated or de-identified information where appropriate.</li></ul><p className="mt-3">We do not connect to your bank account, sell your personal information or use your uploaded evidence for advertising.</p></section>
    <section><h2>AI processing</h2><p>When you request document reading or message generation, relevant case information and uploaded evidence may be processed by our AI service provider to produce the requested result. Automated results can be inaccurate. You must review extracted details and generated text before relying on or sending them.</p></section>
    <section><h2>Service providers and transfers</h2><p>We use service providers for authentication, database and private file storage, website hosting, AI processing and future payment processing. These providers process information on our behalf and may operate in countries different from yours. We use reasonable contractual and technical safeguards appropriate to the service.</p></section>
    <section><h2>Storage and security</h2><p>Evidence is stored in private case folders protected by account-based access controls. We retain information while your account or case is active and for a reasonable period needed for security, dispute handling and legal obligations. No online service can guarantee absolute security.</p></section>
    <section><h2>Your choices and rights</h2><p>Depending on applicable law, you may ask to access, correct, export, restrict or delete your personal information, or object to certain processing. You may also withdraw consent where consent is the basis for processing. Email your request to <a className="font-semibold text-[#0b6b53] underline" href="mailto:contact@myresolvecenter.com">contact@myresolvecenter.com</a>. We may need to verify your identity.</p></section>
    <section><h2>Children</h2><p>MyResolveCenter is not intended for children under 18. We do not knowingly collect personal information from children.</p></section>
    <section><h2>Changes</h2><p>We may update this policy as the service develops. The updated date will appear at the top of this page, and material changes may be communicated through the service.</p></section>
  </LegalPage>;
}
