export type RefundGuide = {
  slug: string;
  name: string;
  title: string;
  description: string;
  routeNote: string;
  steps: string[];
  prepare: string[];
  actionLabel: string;
  actionUrl: string;
  sourceLabel: string;
  sourceUrl: string;
  updatedAt: string;
};

export const refundGuides: RefundGuide[] = [
  {
    slug: "apple",
    name: "Apple",
    title: "How to request an Apple refund",
    description: "Follow the correct route for App Store apps, subscriptions and other content billed by Apple.",
    routeNote: "If Apple processed the payment, submit the request to Apple rather than the app developer.",
    steps: ["Sign in to Apple’s Report a Problem service.", "Choose “Request a refund” and select the reason.", "Select the relevant app, subscription or item and submit.", "Check the request status after submission."],
    prepare: ["Apple receipt or matching charge", "Purchase date and amount", "Apple Account used for the purchase", "A short, factual explanation"],
    actionLabel: "Open Apple refund requests",
    actionUrl: "https://reportaproblem.apple.com/",
    sourceLabel: "Apple’s official refund guidance",
    sourceUrl: "https://support.apple.com/en-us/118223",
    updatedAt: "2026-09-10",
  },
  {
    slug: "google-play",
    name: "Google Play",
    title: "How to request a Google Play refund",
    description: "Check the route for apps, games, in-app purchases and subscriptions billed through Google Play.",
    routeNote: "Google says the available route can depend on what you bought, when you bought it and where you are located.",
    steps: ["Sign in to the Google Account used for the purchase.", "Open the Google Play refund request flow.", "Select the purchase and explain the issue accurately.", "Track the decision; Google says this usually takes one to four days."],
    prepare: ["Google Play order or transaction record", "Purchase date and amount", "Google Account used", "Screenshots supporting the problem"],
    actionLabel: "Open Google Play refund requests",
    actionUrl: "https://support.google.com/googleplay/workflow/9813244?hl=en",
    sourceLabel: "Google Play’s official refund guidance",
    sourceUrl: "https://support.google.com/googleplay/answer/15574897?hl=en",
    updatedAt: "2026-09-10",
  },
  {
    slug: "adobe",
    name: "Adobe",
    title: "How to cancel an Adobe plan and check for a refund",
    description: "Use the Adobe account route for plans bought directly from Adobe, and the original platform for third-party purchases.",
    routeNote: "Adobe directs purchases made through Apple, Google or Microsoft to those providers’ cancellation processes.",
    steps: ["Sign in to your Adobe account.", "Open Plans and payment, then Manage plan.", "Choose Cancel your plan and review the cancellation details.", "Save the confirmation email and check the refund terms for your plan."],
    prepare: ["Adobe invoice or charge", "Plan name", "Purchase or renewal date", "Cancellation confirmation, if available"],
    actionLabel: "Manage an Adobe plan",
    actionUrl: "https://account.adobe.com/plans",
    sourceLabel: "Adobe’s official cancellation guidance",
    sourceUrl: "https://helpx.adobe.com/account/individual/subscriptions-and-plans/renewals-and-cancellations/cancel-adobe-subscription.html",
    updatedAt: "2026-09-10",
  },
  {
    slug: "canva",
    name: "Canva",
    title: "How to handle a Canva subscription charge",
    description: "Identify whether Canva or an app store processed the payment before requesting cancellation or a refund.",
    routeNote: "A Canva subscription purchased through Apple or Google must normally be managed through that platform’s billing route.",
    steps: ["Check the receipt to identify who processed the payment.", "Review the subscription under Billing & plans in your Canva account.", "Cancel future renewal if needed.", "Contact Canva support with the charge details when Canva billed you directly."],
    prepare: ["Receipt or transaction screenshot", "Canva account email", "Charge date and amount", "Cancellation or support messages"],
    actionLabel: "Open Canva support",
    actionUrl: "https://www.canva.com/help/contact-us/",
    sourceLabel: "Canva Help Center",
    sourceUrl: "https://www.canva.com/help/",
    updatedAt: "2026-09-10",
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    title: "How to request a Microsoft purchase refund",
    description: "Find the correct Microsoft route for apps, games, subscriptions and unrecognized account charges.",
    routeNote: "Microsoft uses different routes for PC apps, Xbox purchases, subscriptions and unrecognized charges.",
    steps: ["Sign in to the Microsoft account used for the purchase.", "Find the item in order history or subscription management.", "Use the refund option shown for an eligible item.", "For an unrecognized charge, use Microsoft’s payment investigation route."],
    prepare: ["Microsoft order history or charge", "Order number, if available", "Purchase date and amount", "Reason and supporting screenshots"],
    actionLabel: "Open Microsoft order history",
    actionUrl: "https://account.microsoft.com/billing/orders",
    sourceLabel: "Microsoft’s official refund guidance",
    sourceUrl: "https://support.microsoft.com/en-us/accounts-billing/subscriptions/get-a-refund-for-apps-and-games-purchased-from-microsoft-store",
    updatedAt: "2026-09-10",
  },
  {
    slug: "netflix",
    name: "Netflix",
    title: "How to cancel Netflix and check a charge",
    description: "Cancel a Netflix membership, identify partner billing and prepare a clear request when a charge appears incorrect.",
    routeNote: "If Netflix does not show a cancellation option, its help centre says the membership may be billed through a payment partner that must handle the cancellation.",
    steps: ["Sign in and open Manage your membership.", "Select Cancel, then Finish Cancellation.", "Save the confirmation email and review your payment history.", "If the charge appears incorrect, contact Netflix or the payment partner shown on the account."],
    prepare: ["Netflix account email", "Payment history or transaction screenshot", "Charge date and amount", "Cancellation confirmation, if available"],
    actionLabel: "Manage Netflix membership",
    actionUrl: "https://www.netflix.com/account",
    sourceLabel: "Netflix’s official cancellation guidance",
    sourceUrl: "https://help.netflix.com/en/node/407",
    updatedAt: "2026-10-07",
  },
  {
    slug: "spotify",
    name: "Spotify",
    title: "How to cancel Spotify Premium and check refund options",
    description: "Identify who billed your Spotify plan, stop future renewal and review the published refund route for the charge.",
    routeNote: "Spotify says partner-billed Premium payments must be handled with the partner listed under Your plan. Cancellation normally keeps Premium active until the billing period ends.",
    steps: ["Open your Spotify account and check Your plan.", "Identify whether Spotify or a payment partner billed you.", "Cancel Premium to stop future renewal.", "Review Spotify’s refund policy and contact the correct billing provider if the charge may qualify."],
    prepare: ["Spotify receipt or transaction", "Account email or username", "Plan and billing provider", "Charge date, amount and reason"],
    actionLabel: "Open Spotify account",
    actionUrl: "https://www.spotify.com/account/",
    sourceLabel: "Spotify’s official refund policy",
    sourceUrl: "https://support.spotify.com/us/article/refund-policy/",
    updatedAt: "2026-10-07",
  },
  {
    slug: "amazon-prime",
    name: "Amazon Prime",
    title: "How to cancel Amazon Prime and check for a refund",
    description: "Review your Prime membership, end renewal and ask Amazon about refund eligibility for the current membership period.",
    routeNote: "Prime terms and refund eligibility vary by Amazon marketplace and use of membership benefits. Use the Amazon account and marketplace that billed you.",
    steps: ["Sign in to the Amazon marketplace that charged you.", "Open Prime Membership and review the renewal details.", "Choose the option to update, cancel or end the membership.", "Contact Amazon customer service if you need the charge reviewed for a possible refund."],
    prepare: ["Amazon account email", "Prime charge or invoice", "Marketplace used, such as Amazon.com or Amazon.ae", "Renewal date and any cancellation confirmation"],
    actionLabel: "Manage Amazon memberships",
    actionUrl: "https://www.amazon.com/hz5/yourmembershipsandsubscriptions",
    sourceLabel: "Amazon’s official cancellation guidance",
    sourceUrl: "https://www.aboutamazon.com/news/retail/how-to-cancel-amazon-prime-membership",
    updatedAt: "2026-10-07",
  },
  {
    slug: "youtube-premium",
    name: "YouTube Premium",
    title: "How to request a YouTube Premium refund",
    description: "Check how the membership was billed, cancel future renewal and use the correct Google, Apple or YouTube refund route.",
    routeNote: "YouTube directs Apple-billed purchases to Apple. Google Play and direct YouTube memberships use their respective Google or YouTube support routes.",
    steps: ["Sign in to the Google Account used for the membership.", "Open Paid memberships and check how the payment was processed.", "Cancel the membership if you want to stop renewal.", "Use YouTube’s refund request, Google Play or Apple according to the billing route."],
    prepare: ["Google Account used", "YouTube receipt or payment record", "Membership type", "Charge date, amount and description of the problem"],
    actionLabel: "Open YouTube refund guidance",
    actionUrl: "https://support.google.com/youtube/answer/12014038?hl=en",
    sourceLabel: "YouTube’s official refund guidance",
    sourceUrl: "https://support.google.com/youtube/answer/12014038?hl=en",
    updatedAt: "2026-10-07",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    title: "How to cancel Dropbox and check refund eligibility",
    description: "Identify whether Dropbox or an app store billed the subscription and review the correct cancellation and refund route.",
    routeNote: "Dropbox says most subscription payments are not refundable, but billing errors and applicable regional rights may be reviewed. Storefront purchases must be handled by that storefront.",
    steps: ["Check the receipt to identify Dropbox, Apple or Google as the billing provider.", "Open your Dropbox plan settings and cancel future renewal if needed.", "Review Dropbox’s refund guidance for your location and purchase route.", "Contact Dropbox support or the relevant app store with the transaction details."],
    prepare: ["Dropbox account email", "Invoice or transaction screenshot", "Plan and billing provider", "Charge date and reason for the request"],
    actionLabel: "Open Dropbox support",
    actionUrl: "https://www.dropbox.com/support",
    sourceLabel: "Dropbox’s official refund guidance",
    sourceUrl: "https://help.dropbox.com/plans/refund",
    updatedAt: "2026-10-07",
  },
  {
    slug: "linkedin-premium",
    name: "LinkedIn Premium",
    title: "How to request a LinkedIn Premium refund",
    description: "Cancel a LinkedIn Premium plan, confirm where it was purchased and review the applicable consumer refund policy.",
    routeNote: "LinkedIn’s policy and request route depend on the subscription product, purchase platform, location, timing and use of Premium features.",
    steps: ["Sign in to the LinkedIn account connected to the charge.", "Open Premium subscription settings and check the purchase history.", "Cancel the subscription to prevent the next renewal.", "Review LinkedIn’s refund policy and submit the available request for the relevant product."],
    prepare: ["LinkedIn account email", "Invoice from Purchase History", "Premium product name", "Charge date, amount and reason"],
    actionLabel: "Manage LinkedIn Premium",
    actionUrl: "https://www.linkedin.com/mypreferences/d/premium-manage-account",
    sourceLabel: "LinkedIn’s official refund policy",
    sourceUrl: "https://www.linkedin.com/help/linkedin/answer/a1337140/linkedin-consumer-refund-policy?lang=en",
    updatedAt: "2026-10-07",
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    title: "How to cancel NordVPN and request a refund",
    description: "Stop automatic renewal and check whether a NordVPN purchase falls within its published refund policy.",
    routeNote: "NordVPN publishes a 30-day money-back guarantee for eligible new subscriptions. App-store purchases and renewals can follow different rules and routes.",
    steps: ["Sign in to Nord Account and confirm the purchase date and payment route.", "Cancel automatic renewal if you do not want another charge.", "Review the refund-policy exclusions before submitting the request.", "Contact NordVPN support within the applicable period and retain the response."],
    prepare: ["Nord Account email", "Order or transaction reference", "Purchase date and subscription type", "Payment platform and reason"],
    actionLabel: "Open NordVPN refund help",
    actionUrl: "https://support.nordvpn.com/hc/en-us/sections/38324049616785-Request-a-refund",
    sourceLabel: "NordVPN’s official refund policy",
    sourceUrl: "https://support.nordvpn.com/hc/en-us/articles/19476991311121-What-is-your-refund-policy",
    updatedAt: "2026-10-07",
  },
  {
    slug: "chatgpt",
    name: "ChatGPT",
    title: "How to request a ChatGPT subscription refund",
    description: "Use the correct OpenAI, Apple or Google Play route for a ChatGPT subscription charge and prepare the account details needed for review.",
    routeNote: "The request route depends on where the subscription was purchased. Apple handles Apple subscriptions, while web and eligible Google Play requests use OpenAI’s Help Center process.",
    steps: ["Confirm whether the subscription was purchased on the web, through Apple or through Google Play.", "Sign in with the OpenAI account associated with the charge.", "Cancel future renewal through the same purchase platform.", "Follow the official refund route for that platform and provide the requested billing details."],
    prepare: ["OpenAI account email", "Receipt or invoice number", "Purchase platform", "Charge date, amount and reason"],
    actionLabel: "Open ChatGPT refund guidance",
    actionUrl: "https://help.openai.com/en/articles/7232895-how-do-i-request-a-refund-for-my-chatgpt-subscription",
    sourceLabel: "OpenAI’s official refund guidance",
    sourceUrl: "https://help.openai.com/en/articles/7232895-how-do-i-request-a-refund-for-my-chatgpt-subscription",
    updatedAt: "2026-10-07",
  },
];

export function getRefundGuide(slug: string) {
  return refundGuides.find((guide) => guide.slug === slug);
}
