import type { Metadata } from "next";
import { ArrowRight, Route } from "lucide-react";
import { refundGuides } from "@/lib/refund-guides";

export const metadata: Metadata = { title: "Company Refund Guides", description: "Find the official refund route and evidence checklist for Apple, Google Play, Adobe, Canva and Microsoft purchases.", alternates: { canonical: "/refunds" } };

export default function RefundsPage() {
  return <main className="min-h-screen bg-[#f4f8f6] text-[#13231f]"><header className="border-b bg-white"><div className="mx-auto flex h-18 max-w-6xl items-center justify-between px-5 sm:px-8"><a href="/" className="flex items-center gap-2.5 font-semibold"><span className="grid size-9 place-items-center rounded-xl bg-[#0b6b53] text-white"><Route className="size-5" /></span>MyResolveCenter</a><a href="/#assessment" className="text-sm font-semibold text-[#0b6b53]">Check my charge</a></div></header><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20"><p className="text-sm font-bold uppercase tracking-[.13em] text-[#0b8062]">Company refund routes</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Start with the company or platform that processed your payment.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#5b6d67]">Each guide links to an official company process and shows the information to prepare before submitting your request.</p><div className="mt-10 grid gap-4 md:grid-cols-2">{refundGuides.map((guide) => <a key={guide.slug} href={`/refunds/${guide.slug}`} className="group rounded-2xl border border-[#dce6e2] bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-[#8db5a7] hover:shadow-md"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#0b8062]">{guide.name}</p><h2 className="mt-2 text-xl font-semibold">{guide.title}</h2><p className="mt-3 leading-7 text-[#5b6d67]">{guide.description}</p><span className="mt-5 inline-flex items-center gap-2 font-semibold text-[#0b6b53]">View refund guide <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a>)}</div></div></main>;
}
